# Debug Rebin

- Sylvie Dagoret-Campagne
- creation date September 2023-09-07


In [17]:
from spectractor.tools import (plot_image_simple, save_fits, load_fits, fit_poly1d, plot_compass_simple,
                               fit_poly1d_outlier_removal, weighted_avg_and_std,
                               fit_poly2d_outlier_removal, hessian_and_theta,
                               set_wcs_file_name, load_wcs_from_file, imgslice, rebin)
from spectractor import parameters
import numpy as np

In [2]:
#a = 4 * np.ones((10, 10))
a = np.arange(100).reshape((10,10))

In [3]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [4]:
np.asarray(a.shape)

array([10, 10])

In [19]:
REBIN = 2
parameters.CCD_REBIN = REBIN

In [6]:
new_shape = (a.shape[0]//REBIN,a.shape[1]//REBIN)
new_shape = np.asarray(new_shape)
new_shape

array([5, 5])

In [7]:
if np.any(new_shape * REBIN != a.shape):
    shape_cropped = new_shape * REBIN
    margins = np.asarray(a.shape) - shape_cropped
    print("margins = ",margins)
    a = a[:-margins[0], :-margins[1]]


In [8]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [9]:
shape = (new_shape[0], a.shape[0] // new_shape[0],new_shape[1], a.shape[1] // new_shape[1])

In [10]:
shape

(5, 2, 5, 2)

In [11]:
a.reshape(shape).sum(-1).sum(1)

array([[ 22,  30,  38,  46,  54],
       [102, 110, 118, 126, 134],
       [182, 190, 198, 206, 214],
       [262, 270, 278, 286, 294],
       [342, 350, 358, 366, 374]])

In [12]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
a.reshape(shape).mean(-1).mean(1)

array([[ 5.5,  7.5,  9.5, 11.5, 13.5],
       [25.5, 27.5, 29.5, 31.5, 33.5],
       [45.5, 47.5, 49.5, 51.5, 53.5],
       [65.5, 67.5, 69.5, 71.5, 73.5],
       [85.5, 87.5, 89.5, 91.5, 93.5]])

In [14]:
a.reshape(shape).sum(-1).sum(1)/4.

array([[ 5.5,  7.5,  9.5, 11.5, 13.5],
       [25.5, 27.5, 29.5, 31.5, 33.5],
       [45.5, 47.5, 49.5, 51.5, 53.5],
       [65.5, 67.5, 69.5, 71.5, 73.5],
       [85.5, 87.5, 89.5, 91.5, 93.5]])

In [20]:
b = rebin(a, new_shape,FLAG_MAKESUM=True)

REBIN DO MAKESUM


In [21]:
b

array([[ 22,  30,  38,  46,  54],
       [102, 110, 118, 126, 134],
       [182, 190, 198, 206, 214],
       [262, 270, 278, 286, 294],
       [342, 350, 358, 366, 374]])

In [17]:
b = rebin(a, new_shape,FLAG_MAKESUM=False)

REBIN DO MAKEMEAN


In [18]:
b

array([[ 0.,  1.,  2.,  3.,  4.],
       [10., 11., 12., 13., 14.],
       [20., 21., 22., 23., 24.],
       [30., 31., 32., 33., 34.],
       [40., 41., 42., 43., 44.]])